#!/bin/sh

g++ -std=c++11 -c ./src/Utilities.cpp -o ./src/Utilities.o
g++ -std=c++11 -c ./src/EODRecord.cpp -o ./src/EODRecord.o
g++ -std=c++11 -c ./src/SalesOrder.cpp -o ./src/SalesOrder.o
g++ -std=c++11 -c ./src/Customer.cpp -o ./src/Customer.o

g++ -std=c++11 -o ordering ./src/main.cpp ./src/Customer.o ./src/SalesOrder.o ./src/EODRecord.o ./src/Utilities.o

rm ./src/Customer.o ./src/SalesOrder.o ./src/EODRecord.o ./src/Utilities.o
